"""Initial migration

Revision ID: 06eeb7dd37ee
Revises: 13d5883aa845
Create Date: 2023-07-05 16:47:56.980029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06eeb7dd37ee'
down_revision = '13d5883aa845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chercheur', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['passwd_che'])

    with op.batch_alter_table('expert', schema=None) as batch_op:
        batch_op.alter_column('dispo',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['passwd_exp'])

    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.alter_column('sujet',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.alter_column('sujet',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('expert', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('dispo',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    with op.batch_alter_table('chercheur', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
