"""Initial migration

Revision ID: 13d5883aa845
Revises: 5cb068083c89
Create Date: 2023-07-05 16:17:22.788036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d5883aa845'
down_revision = '5cb068083c89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projet',
    sa.Column('id_prj', sa.Integer(), nullable=False),
    sa.Column('sujet', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file', sa.LargeBinary(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('fk_projet_cher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_projet_cher_id'], ['chercheur.id_che'], ),
    sa.PrimaryKeyConstraint('id_prj')
    )
    with op.batch_alter_table('chercheur', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['passwd_che'])

    with op.batch_alter_table('expert', schema=None) as batch_op:
        batch_op.alter_column('dispo',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['passwd_exp'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expert', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('dispo',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    with op.batch_alter_table('chercheur', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('projet')
    # ### end Alembic commands ###
